### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by hannorein** [Smithsonian/SuperNOVAS#14]
I easily get confused with times systems but I think there is a typo in [this example](https://smithsonian.github.io/SuperNOVAS/apidoc/html/index.html#autotoc_md20) in the documentation:

```c
// Calculate the Terrestrial Time (TT) based Julian date of observation (in days)
// Let's say on 2024-02-06 at 14:53:06 UTC.
double jd_tt = julian_date(2024, 2, 6, 14.885) + get_utc_to_tt(leap_seconds) / 86400.0; 
 
// We'll also need the TT - UT1 difference, which we can obtain from what we already
// defined above
double ut1_to_tt = get_ut1_to_tt(jd_tt, dut1);
```

The first argument to `get_ut1_to_tt` in the example is TT, but I think it should be `leap_seconds` according to the [documentation of the function itself](https://smithsonian.github.io/SuperNOVAS/apidoc/html/novas_8c.html#a4d7470ca705efa1953e8b4beab77c6b6).

**Comment by attipaci** [comment]
Thanks @hannorein,

I got that corrected. :-)
