### ISSUE TITLE
Numerical value of AU

### ISSUE THREAD

**Issue by hannorein** [Smithsonian/SuperNOVAS#18]
Not a huge issue, but do you have any thought on whether it would make sense to update the value of AU to the one adopted by the IAU? It's not a huge difference...

```
149597870.7 
149597870.69098932
```

**Comment by attipaci** [comment]
Yes, I think that would make sense. It's not going to make a huge difference, but might as well use the more precise value. I'll add the change onto the `v1.0.1` branch.
