### ISSUE TITLE
should it need doxygen by default?

### ISSUE THREAD

**Issue by teuben** [Smithsonian/SuperNOVAS#21]
A default

     make

told me I needed doxygen.    Should there be a default make that just compiles?  Of course it worked after I installed it, but I'd like to argue the default should not.

**Comment by attipaci** [comment]
Hi Peter,

The default `make` target is the 'api', which includes the static and shared libraries, the `cio_bin` file and the doxygen documentation. I don't think it's very relevant what the default build target is. You can pick and choose each individually. Quoting from the `README`:

> you can build select components of the above with the make targets `static`, `shared`, `cio_file`, and `dox` respectively

So, if you want just the static library, just use

```bash
 $ make static
```

And, if there is a good reason why the default build target should be different, then that change can be made to the next feature release (e.g. 1.1.0). It will however require adjusting the both the documentation and the CI to match...

I hope that answers the question,

-- Attila.

**Comment by attipaci** [comment]
PS. Alternatively, I could make the `dox` part of the build conditional on the presence of `doxygen`. That way nothing much else needs to change beyong the `Makefile`...

**Comment by teuben** [comment]
fair enough.   But as you get older and use more and more makefiles, it gets tedious to "more" the makefile.   SO I'm now using a technique advocated by software carpentry to make the makefile self-documenting. I mean, who wants to read a README when there's a Makefile :-)     You can add that as the first "help" target.  I now employ this to all my (new) projects. Here's an example of that implementation

https://github.com/teuben/teunix/blob/master/Makefile

**Comment by teuben** [comment]
yes, that sounds like a good compromise.
