### ISSUE TITLE
NOVAS_TAI_TO_TT definition off by 3 ms

### ISSUE THREAD

**Issue by kiranshila** [Smithsonian/SuperNOVAS#64]
Hey there, fantastic work on this library! I'm glad someone is modernizing NOVAS a bit and cleaning up some ancient bugs.

Quick question on https://github.com/Smithsonian/SuperNOVAS/blob/79c356934ad9fb278eaee4d1dcfd6611d485395e/include/novas.h#L165

I think this is wrong? I believe the official spec is TT is ahead of TAI by exactly 32.184s, not 32.187s.

**Comment by attipaci** [comment]
Yes, good catch! Lucky it's the last decimal that went bad :-). I have committed an pushed the fix to `main` at c652f7c, and will include it in the next release candidate in a week or two. Let me know if you find anything else amiss :-).

**Comment by kiranshila** [comment]
Great stuff! Thanks!

I'm working on a high-level Rust wrapper around this for potential use in the DSA-2000 telescope, so I'll be reading through a lot of the source haha. I'll send PRs as I find things :)

I'm looking through the time stuff right now, as I'm just going to provide conversion routines from Rust's [hifitime](https://docs.rs/hifitime/latest/hifitime/).

Again, fantastic work on all this!

**Comment by attipaci** [comment]
That sounds like a fun project. I look forward to the PRs. ;-)

**Comment by attipaci** [comment]
PS. Thanks also for your expression of appreciation. It feels good to know the effort is not in vain ;-)
