### ISSUE TITLE
C++ Style Comments Conflicts with C90 Standard

### ISSUE THREAD

**Issue by kiranshila** [Smithsonian/SuperNOVAS#65]
Attempting to compile with `-std=c90` to check the claim that the codebase is `compatible with the C90 standard` results is many errors around C++ style (`\\`) comments. 

I more than happy to fix these by replacing with C90 comments (`\**\`) or would you consider bumping up the C standard to C99 to support the C++ style?

**Comment by attipaci** [comment]
I'd vote for just bumping to C99. I'll update the docs as such.

Strange though that gcc 2.9 (1998) on an old LynxOS/PowerPC does not barf on it (we still use that on some machines at the SMA). Perhaps, it already using the C99 standard? (I just assumed it was C90 given its age).

**Comment by kiranshila** [comment]
I think C99 is a good idea - it's the current JPL coding standards target. IIRC old GCC silently supports these comment styles and only complains when you explicitly supply the standard with `-std`

**Comment by attipaci** [comment]
Updated docs to C99 at ffc8e40
