### ISSUE TITLE
Unused accuracy in cirs/tod conversions

### ISSUE THREAD

**Issue by kiranshila** [Smithsonian/SuperNOVAS#67]
In https://github.com/Smithsonian/SuperNOVAS/blob/59a40e4e74844ffbb5367cab6dc25a6dcd77350f/src/super.c#L381-L423

the `accuracy` argument is unused, and the call to `cio_ra` is hard-coded to `NOVAS_FULL_ACCURACY`. Is this intentional?

**Comment by attipaci** [comment]
Good catch again. Yes, that's my bad. I'll change `NOVAS_FULL_ACCURACY` to `accuracy` on l.420. Fixed on `main` at 669a51d

**Comment by kiranshila** [comment]
Great! A fine example on why explicitly tagging intentionally unused inputs in helpful :)

**Comment by kiranshila** [comment]
@attipaci I believe we also need to fix it here as well
https://github.com/Smithsonian/SuperNOVAS/blob/31cb5ec7d2917622bae1c2222ebe667f17850135/src/super.c#L387
